name: update hatenablog sitemap

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 11 * * *'

jobs:
  check-and-post-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : post to google search console
        shell: bash
        run : |
          php -v 
          MY_ENCRYPT_KEY=${{ secrets.MY_ENCRYPT_KEY }} php update-sitemap.php
      - name : log
        shell: bash
        run : |
          date -I > last-update-sitemap.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: update-sitemap
