name: update hatenablog sitemap

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '12 12 * * 1'

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : post to google search console
        shell: bash
        run : |
          php -v 
          MY_ENCRYPT_KEY=${{ secrets.MY_ENCRYPT_KEY }} php update-sitemap.php
