name: notify to google

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 12 * * *'

jobs:
  check-sitemap-and-web-ping:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : web-ping
        shell: bash
        run : |
          php -v 
          php web-ping.php
      - name : log
        shell: bash
        run : |
          date -I > last-webping.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: update webping
